program ::= PROGRAM ID SEMI block DOT

block ::= declarations compound_statement

declarations ::= VAR (variable_declaration SEMI)+
                 | empty

variable_declaration ::= multiple_variable COLON type_spec

multiple_variable ::= ID (COMMA ID)* 
                  | ID (COMMA ID) multiple_variable

type_spec ::= INTEGER | REAL

compound_statement ::= BEGIN statement_list END

statement_list ::= statement
               | statement SEMI statement_list

statement ::= compound_statement
          | assignment_statement
          | function_statement
          | empty

function_statement ::= PROCEDURE function_declaration

function_declaration ::= ID (parameter_list)* function_body

parameter_list ::= parameter | parameter SEMI parameter_list

function_body ::= block


assignment_statement ::= variable ASSIGN expr

empty ::=

expr::= term ((PLUS | MINUS) term)*

term::= factor ((MUL | DIV) factor)*

factor ::= PLUS factor
       | MINUS factor
       | INTEGER
       | LPAREN expr RPAREN
       | variable

variable::= ID